[package]
name = "vdu"
version = "0.1.0"
edition = "2018"

[dependencies]
bytesize = "*"
http_io = { version = "^0.2.10", default-features = false, features = ["std"]}
indicatif = "*"
log = "*"
num-format = "*"
bincode = "*"
tar = "*"
vdu_path_tree = { version = "*", path = "../vdu_path_tree" }
walkdir = "*"
